### ISSUE TITLE
Linked command failed

### ISSUE THREAD

**Issue by sacOO7** [alibaba/HandyJSON#294]
Swift version - **4.1.2**

I am currently trying to compile code using latest version of this library - **4.2.0** .
I am getting some linking error 

```
Undefined symbols for architecture x86_64:
  "_swift_getFieldAt", referenced from:
      HandyJSON.Metadata.Class._propertyDescriptionsAndStartPoint() -> ([HandyJSON.Property.Description], Swift.Int32?)? in Metadata.o
      HandyJSON.Metadata.Struct.propertyDescriptions() -> [HandyJSON.Property.Description]? in Metadata.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

It works fine with library version - **4.1.0**
It will be really helpful if you can give solution to above problem. Thank you :)

**Comment by sacOO7** [comment]
Hi, @xuyecan , @cijianzy any updates on this? I really need your help

**Comment by sacOO7** [comment]
Hi guys, any update on this? or no one is maintaining this project?

**Comment by chenxing890** [comment]
I also encountered this problem.

**Comment by winterrain5** [comment]
> Can anyone please help us on this? It's really necessary for my project.

try using  pod 'HandyJSON', '~> 4.1.1' ,it will fix this problem

**Comment by shijian123** [comment]
我这边设置了还是不行呀，xcode10.2beta版本

**Comment by cijianzy** [comment]
可以加qq群@群主看下，我估计他看github机会不多。

**Comment by lynnleelhl** [comment]
Xcode 9+ or previous version: checkout tag 4.1.3
Xcode 10.0/10.1: checkout master branch
Xcode 10.2beta: try branch dev_for_swift5.0

Notice that Swift version showed in your Build Settings has nothing to do with your compile issue, Swift compiler version is depend on your Xcode version.

**Comment by SanyasiraoM** [comment]
any update on this?

**Comment by UncleAdamShaw** [comment]
Use version 4.1.3, it works for me

**Comment by ifanchu** [comment]
xCode 10.1(10B61), use 4.2.1.
